# Configuration Keepalived - Serveur Secondaire (mail2)
# Nœud : 192.168.1.11 | IP Flottante : 192.168.1.100

vrrp_script chk_mail_services {
    script "/usr/local/bin/check_mail_health.sh"
    interval 2
    weight -20
    fall 2
    rise 2
}

vrrp_instance VI_MAIL {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 90               # Priorité 90 (prend le relais dès que mail1 passe à 80 ou crash)
    nopreempt
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass SECURE_VRRP_PASS
    }

    virtual_ipaddress {
        192.168.1.100/24 dev eth0
    }

    track_script {
        chk_mail_services
    }

    notify_master "/usr/bin/logger -t keepalived 'mail2 a pris le statut MASTER (IP 192.168.1.100 active)'"
    notify_backup "/usr/bin/logger -t keepalived 'mail2 a basculé en statut BACKUP'"
    notify_fault  "/usr/bin/logger -t keepalived 'mail2 est en FAULT suite à incident de service'"
}
